# Generated by Django 5.2.4 on 2025-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('refrence_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=10)),
                ('reader_contact', models.CharField(max_length=10, null=True)),
                ('reader_address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
